crm1/urls.py
from django.conf.urls import url, include
from . import views
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

app_name = 'crm1'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('customer/<int:pk>/summary/', views.summary, name='summary'),
    path('prod', views.prod, name='prod'),
    path('product/create/', views.product_new, name='product_new'),
    path('product/<int:pk>/edit/', views.product_edit, name='product_edit'),
    path('product/<int:pk>/delete/', views.product_delete, name='product_delete'),
    #path('login/', auth_views.LoginView.as_view(template_name='crm1/login.html'), name='login'),
    path('contact', views.contact, name='contact'),
    path('accounts/', include('django.contrib.auth.urls')),

]

crm1/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from django.db import models


# Create your models here.
class Customer(models.Model):
    cust_name = models.CharField(max_length=50)
    organization = models.CharField(max_length=100, blank=True)
    role = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    bldgroom = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    account_number = models.IntegerField(blank=False, null=False)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=50)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.cust_name)



class Product(models.Model):
    cust_name = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='products')
    product = models.CharField(max_length=100)
    p_description = models.TextField()
    quantity = models.IntegerField()
    pickup_time = models.DateTimeField(
        default=timezone.now)
    charge = models.DecimalField(max_digits=10, decimal_places=2)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.cust_name)

crm1/forms.py
from django import forms
from .models import Customer, Product

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('cust_name', 'organization', 'role', 'bldgroom', 'account_number', 'address',
                      'city', 'state', 'zipcode', 'email','phone_number')


class ProductForm(forms.ModelForm):
   class Meta:
       model = Product
       fields = ('cust_name', 'product', 'p_description', 'quantity', 'pickup_time', 'charge')

crm1/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.db.models import Sum
from _decimal import Decimal

import csv

from django.http import HttpResponse


now = timezone.now()
def home(request):
   return render(request, 'crm1/home.html',
                 {'crm1': home})


def login(request):
   return render(request, 'crm1/templates/registration/login.html',
                 {'crm1': login})

@login_required
def customer_list(request):
    customer = Customer.objects.filter(created_date__lte=timezone.now())
    return render(request, 'crm1/customer_list.html',
                 {'customers': customer})

def contact(request):
    return render(request, 'crm1/contact.html')


@login_required
def customer_edit(request, pk):
   customer = get_object_or_404(Customer, pk=pk)
   if request.method == "POST":
       # update
       form = CustomerForm(request.POST, instance=customer)
       if form.is_valid():
           customer = form.save(commit=False)
           customer.updated_date = timezone.now()
           customer.save()
           customer = Customer.objects.filter(created_date__lte=timezone.now())
           return render(request, 'crm1/customer_list.html',
                         {'customers': customer})
   else:
        # edit
       form = CustomerForm(instance=customer)
   return render(request, 'crm1/customer_edit.html', {'form': form})

@login_required
def customer_delete(request, pk):
   customer = get_object_or_404(Customer, pk=pk)
   customer.delete()
   return redirect('crm1:customer_list')





def prod(request):
   products = Product.objects.filter(created_date__lte=timezone.now())
   return render(request, 'crm1/prod.html', {'products': products})



@login_required
def product_new(request):
   if request.method == "POST":
       form = ProductForm(request.POST)
       if form.is_valid():
           product = form.save(commit=False)
           product.created_date = timezone.now()
           product.save()
           products = Product.objects.filter(created_date__lte=timezone.now())
           return render(request, 'crm1/prod.html',
                         {'products': products})
   else:
       form = ProductForm()
       # print("Else")
   return render(request, 'crm1/product_new.html', {'form': form})


@login_required
def product_edit(request, pk):
   if request.method == "POST":
       form = ProductForm(request.POST, instance=product)
       if form.is_valid():
           product = form.save()
           product.updated_date = timezone.now()
           product.save()
           products = Product.objects.filter(created_date__lte=timezone.now())
           return render(request, 'crm1/prod.html', {'products': products})
   else:
       # print("else")
       form = ProductForm(instance=product)
   return render(request, 'crm1/product_edit.html', {'form': form})


@login_required
def product_delete(request, pk):
   product = get_object_or_404(Product, pk=pk)
   product.delete()
   return redirect('crm1:product_list')


@login_required
def summary(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customers = Customer.objects.filter(created_date__lte=timezone.now())
    products = Product.objects.filter(cust_name=pk)
    sum_product_charge = \
        Product.objects.filter(cust_name=pk).aggregate(Sum('charge'))


    return render(request, 'crm1/summary.html', {'customer': customer,
                              'products': products,
                              'sum_product_charge': sum_product_charge,})


@login_required
def export_customers(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="customers.csv"'

    writer = csv.writer(response)
    writer.writerow(['cust_name', 'organization', 'role', 'email', 'phone_number', 'bldgroom', 'account_number', 'address', 'city', 'state', 'zipcode'])

    customers = Customer.objects.all().values_list('cust_name', 'organization', 'role', 'email', 'phone_number', 'bldgroom', 'account_number', 'address', 'city', 'state', 'zipcode')
    for customer in customers:
        writer.writerow(customer)

    return response
from django.shortcuts import render

# Create your views here.

crm1/templates/crm1/base.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'crm1/main.css' %}">

<html lang="en">
<head>


    <title>Dog Bites</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'crm1/main.css' %}">
    <link href="crm1/main.css" rel="stylesheet" type="text/css" media="screen,projection" >

    <style>
        /*
GENERAL
*/
a {
    text-decoration: none;
    }

   img {
   max-width: 100%;

   }



    body {
      font-family: 'Libre Baskerville', serif;
      font-size: 16px;
      margin: 10px;
    }


    #wrapper {
      max-width: 940px;
      margin: 0 auto;
      padding: 0 5%;

    }



    a {
      color: #000;

    }

    h3 {
        margin: 0 0 1em 0;
    }


   /*
   HEADING
   */

   header {
     float: left;
     margin: 0 0 20px 0;
     padding: 2px 0 0 0;
     width: 100%;

   }



   #logo {
      text-align: center;
      margin: 0;

    }

    h1  {
    font-family: 'Fjalla One', sans-serif;
    margin: 10px 0;
    font-size: 46px;
    font-weight: normal;
    line-height: 0.5;
    text-align: center;
    color: 	#000;

    }

    h2  {


    font-size: 1.00em;
    font-weight: normal;
    text-align: center;
    margin: -5px 0 0;
    }


   h3  {


       font-size: 1.1em;
       font-weight: 700;
       text-align: center;
       margin: 15px 0 0;
   }




/*
NAVIGATION
*/
/* Add a black background color to the top navigation */
.navbar {
  background-color: #a28e73;
  overflow: hidden;
}

/* Style the links inside the navigation bar */
.navbar a {
  float: left;
  color: black;
  text-align: right;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

/* Change the color of links on hover */
.navbar a:hover {
  background-color: #e6ccb2;
  color: black;
}



   /*
   FOOTER
   */
    footer {
    font-size: 0.75em;
    text-align: center;
    clear: both;
    padding-top: 50px;
    color: white;
    }



   /*
   PAGE:
   */
   .mydiv {background: white; width:250px; height: 250px;}

   .myimage {
       float:left;
       width:300px;
       height:350px;
       margin:20px;
       border-radius: 0px;
       border-style: solid;
       border-color: #ab8c6d;
       border-width: 5px;
   }



   /* IMAGES */
  /* Three image containers (use 25% for four, and 50% for two, etc) */
  .column {
    float: left;
    width: 33.33%;
    padding: 5px;
  }

  /* Clear floats after image containers */
  .row::after {
    content: "";
    clear: both;
    display: table;
  }



    /*
   PAGE: ABOUT
   */
   .myimage {
       display: block;
       max-width: 400px;
       margin: 20px;
       border-radius: 0px;
       border-style: solid;
       border-color: #ab8c6d;
       border-width: 5px;
   }


   .button {
    background-color: #5f4c3e;
    border: none;
    color: white;
    padding: 10px 20px;
    text-align: center;
    text-decoration: none;
    display: block;
    margin: 4px 2px;
    cursor: pointer;
    border-radius: 16px;
    justify-content: center;
  }

   /*
   COLORS
   */


    /* header */
     header {
      background: #000;
      border-color: #000;
    }

    /* logo text*/

    h1,h2  {
       color: #000;
   }

   /* nav background on mobile devices*/
   nav {
      background: #e5d3bb;
   }

   nav a, nav a:visited {
       color: #5f4c3e;
   }

   /* selected nav link color*/
   nav a.selected, nav a:hover {
     color: #000;
   }
   /* site body*/
   body {
       background-color: white;
       color: #000;
   }


  /*SHOP*/
  * {
    box-sizing: border-box;
  }

  body {
    background-color: #f1f1f1;
    padding: 20px;
    font-family: Arial;
  }

  /* Center website */
  .main {
    max-width: 1000px;
    margin: auto;
  }

  h1 {
    font-size: 50px;
    word-break: break-all;
  }

  .row {
    margin: 8px -16px;
  }

  /* Add padding BETWEEN each column (if you want) */
  .row,
  .row > .column {
    padding: 8px;
  }

  /* Create four equal columns that floats next to each other */
  .column {
    float: left;
    width: 25%;
  }

  /* Clear floats after rows */
  .row:after {
    content: "";
    display: table;
    clear: both;
  }

  /* Content */
  .content {
    background-color: white;
    padding: 10px;
  }

  /* Responsive layout - makes a two column-layout instead of four columns */
  @media screen and (max-width: 900px) {
    .column {
      width: 50%;
    }
  }

  /* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
  @media screen and (max-width: 600px) {
    .column {
      width: 100%;
    }
  }


  /*contact us*/
  /* Style inputs with type="text", select elements and textareas */
  input[type=text], select, textarea {
    width: 100%; /* Full width */
    padding: 12px; /* Some padding */
    border: 1px solid #ccc; /* Gray border */
    border-radius: 4px; /* Rounded borders */
    box-sizing: border-box; /* Make sure that padding and width stays in place */
    margin-top: 6px; /* Add a top margin */
    margin-bottom: 16px; /* Bottom margin */
    resize: vertical /* Allow the user to vertically resize the textarea (not horizontally) */
  }

  /* Style the submit button with a specific background color etc */
  input[type=submit] {
    background-color: #5f4c3e;
    color: white;
    padding: 12px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  /* When moving the mouse over the submit button, add a darker green color */
  input[type=submit]:hover {
    background-color: #5f4c3e;
  }

  /* Add a background color and some padding around the form */
  .container {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
  }



  /* Bordered form */
form {
  border: 3px solid #f1f1f1;
}

/* Full-width inputs */
input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

/* Set a style for all buttons */
button {
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

/* Add a hover effect for buttons */
button:hover {
  opacity: 0.8;
}

/* Extra style for the cancel button (red) */
.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}


/* Add padding to containers */
.container {
  padding: 16px;
}

/* The "Forgot password" text */
span.psw {
  float: right;
  padding-top: 16px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
    display: block;
    float: none;
  }
  .cancelbtn {
    width: 100%;
  }
}


    </style>






</head>
<body>

<br>
<br>

<div class="navbar">
    <ul>
  <a href="{% url 'crm1:home' %}">Home</a>
  <a href="{% url 'crm1:contact' %}">Contact</a>
        <a href="{% url 'crm1:prod' %}">Shop</a>
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a>
                {% else %}
                    <a href="{% url 'crm1:login' %}">Login</a>
                {% endif %}
    </ul>



</div>


<h1>Dog Bites</h1>
<h3>home baked treats for your furry friend</h3>


<br>
<br>
  <div id="wrapper">
    <div class="row">
      <div class="column">
        <img src="Layla_Cookies.png">
      </div>
      <div class="column">
        <img src="Chicken_Cookies.png">
      </div>
      <div class="column">
        <img src="Dog_Cookies.png">
      </div>
    </div>
  </div>



  <br>
  <br>
  <button class="button">Shop Now</button>




</body>
</html>

crm1/templates/crm1/contact.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'crm1/main.css' %}">
<html lang="en">
<head>

        <style>
        /*
GENERAL
*/
a {
    text-decoration: none;
    }

   img {
   max-width: 100%;

   }



    body {
      font-family: 'Libre Baskerville', serif;
      font-size: 16px;
      margin: 10px;
    }


    #wrapper {
      max-width: 940px;
      margin: 0 auto;
      padding: 0 5%;

    }



    a {
      color: #000;

    }

    h3 {
        margin: 0 0 1em 0;
    }


   /*
   HEADING
   */

   header {
     float: left;
     margin: 0 0 20px 0;
     padding: 2px 0 0 0;
     width: 100%;

   }



   #logo {
      text-align: center;
      margin: 0;

    }

    h1  {
    font-family: 'Fjalla One', sans-serif;
    margin: 10px 0;
    font-size: 46px;
    font-weight: normal;
    line-height: 0.5;
    text-align: center;
    color: 	#000;

    }

    h2  {


    font-size: 1.00em;
    font-weight: normal;
    text-align: center;
    margin: -5px 0 0;
    }


   h3  {


       font-size: 1.1em;
       font-weight: 700;
       text-align: center;
       margin: 15px 0 0;
   }




/*
NAVIGATION
*/
/* Add a black background color to the top navigation */
.navbar {
  background-color: #a28e73;
  overflow: hidden;
}

/* Style the links inside the navigation bar */
.navbar a {
  float: left;
  color: black;
  text-align: right;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

/* Change the color of links on hover */
.navbar a:hover {
  background-color: #e6ccb2;
  color: black;
}



   /*
   FOOTER
   */
    footer {
    font-size: 0.75em;
    text-align: center;
    clear: both;
    padding-top: 50px;
    color: white;
    }



   /*
   PAGE:
   */
   .mydiv {background: white; width:250px; height: 250px;}

   .myimage {
       float:left;
       width:300px;
       height:350px;
       margin:20px;
       border-radius: 0px;
       border-style: solid;
       border-color: #ab8c6d;
       border-width: 5px;
   }



   /* IMAGES */
  /* Three image containers (use 25% for four, and 50% for two, etc) */
  .column {
    float: left;
    width: 33.33%;
    padding: 5px;
  }

  /* Clear floats after image containers */
  .row::after {
    content: "";
    clear: both;
    display: table;
  }



    /*
   PAGE: ABOUT
   */
   .myimage {
       display: block;
       max-width: 400px;
       margin: 20px;
       border-radius: 0px;
       border-style: solid;
       border-color: #ab8c6d;
       border-width: 5px;
   }


   .button {
    background-color: #5f4c3e;
    border: none;
    color: white;
    padding: 10px 20px;
    text-align: center;
    text-decoration: none;
    display: block;
    margin: 4px 2px;
    cursor: pointer;
    border-radius: 16px;
    justify-content: center;
  }

   /*
   COLORS
   */


    /* header */
     header {
      background: #000;
      border-color: #000;
    }

    /* logo text*/

    h1,h2  {
       color: #000;
   }

   /* nav background on mobile devices*/
   nav {
      background: #e5d3bb;
   }

   nav a, nav a:visited {
       color: #5f4c3e;
   }

   /* selected nav link color*/
   nav a.selected, nav a:hover {
     color: #000;
   }
   /* site body*/
   body {
       background-color: white;
       color: #000;
   }


  /*SHOP*/
  * {
    box-sizing: border-box;
  }

  body {
    background-color: #f1f1f1;
    padding: 20px;
    font-family: Arial;
  }

  /* Center website */
  .main {
    max-width: 1000px;
    margin: auto;
  }

  h1 {
    font-size: 50px;
    word-break: break-all;
  }

  .row {
    margin: 8px -16px;
  }

  /* Add padding BETWEEN each column (if you want) */
  .row,
  .row > .column {
    padding: 8px;
  }

  /* Create four equal columns that floats next to each other */
  .column {
    float: left;
    width: 25%;
  }

  /* Clear floats after rows */
  .row:after {
    content: "";
    display: table;
    clear: both;
  }

  /* Content */
  .content {
    background-color: white;
    padding: 10px;
  }

  /* Responsive layout - makes a two column-layout instead of four columns */
  @media screen and (max-width: 900px) {
    .column {
      width: 50%;
    }
  }

  /* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
  @media screen and (max-width: 600px) {
    .column {
      width: 100%;
    }
  }


  /*contact us*/
  /* Style inputs with type="text", select elements and textareas */
  input[type=text], select, textarea {
    width: 100%; /* Full width */
    padding: 12px; /* Some padding */
    border: 1px solid #ccc; /* Gray border */
    border-radius: 4px; /* Rounded borders */
    box-sizing: border-box; /* Make sure that padding and width stays in place */
    margin-top: 6px; /* Add a top margin */
    margin-bottom: 16px; /* Bottom margin */
    resize: vertical /* Allow the user to vertically resize the textarea (not horizontally) */
  }

  /* Style the submit button with a specific background color etc */
  input[type=submit] {
    background-color: #5f4c3e;
    color: white;
    padding: 12px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  /* When moving the mouse over the submit button, add a darker green color */
  input[type=submit]:hover {
    background-color: #5f4c3e;
  }

  /* Add a background color and some padding around the form */
  .container {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
  }



  /* Bordered form */
form {
  border: 3px solid #f1f1f1;
}

/* Full-width inputs */
input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

/* Set a style for all buttons */
button {
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

/* Add a hover effect for buttons */
button:hover {
  opacity: 0.8;
}

/* Extra style for the cancel button (red) */
.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}


/* Add padding to containers */
.container {
  padding: 16px;
}

/* The "Forgot password" text */
span.psw {
  float: right;
  padding-top: 16px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
    display: block;
    float: none;
  }
  .cancelbtn {
    width: 100%;
  }
}


    </style>

    <meta charset="UTF-8">

    <title>Dog Bites</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'crm1/main.css' %}">
    <link href="crm1/main.css" rel="stylesheet" type="text/css" media="screen,projection" >

<div class="navbar">
    <ul>
  <a href="{% url 'crm1:home' %}">Home</a>
  <a href="{% url 'crm1:contact' %}">Contact</a>
        <a href="{% url 'crm1:prod' %}">Shop</a>
        <a href="{% url 'crm1:login' %}">Login</a>
    </ul>


</div>


</head>
<body>

<br>
<br>



<br>

<div>
    <h1>We would love to hear from you!</h1>
    <br>
    <h2>Please fill out this contact form to hear from us and place any orders for your next special celebration!</h2>
</div>


<div class="container">
    <form action="action_page.php">

      <label for="fname">First Name</label>
      <input type="text" id="fname" name="firstname" placeholder="Your name..">

        <br>
        <br>

      <label for="lname">Last Name</label>
      <input type="text" id="lname" name="lastname" placeholder="Your last name..">

        <br>
        <br>

      <label for="email">E-Mail Address</label>
      <input type="text" id="lname" name="lastname" placeholder="Your e-mail address..">

        <br>
        <br>

      <label for="state">State</label>
      <select id="state" name="state">
        <option value="nebraska">Nebraska</option>
        <option value="iowa">Iowa</option>
        <option value="kansas">Kansas</option>
      </select>

        <br>
        <br>

      <label for="order">Order Details</label>
      <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>

        <br>
        <br>

      <input type="submit" value="Submit">

    </form>
  </div>

crm1/templates/crm1/customer_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ customer.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm1:home' pk=customer.cust_number %} ">Cancel</a>

    </form>

{% endblock %}

</html>

crm1/templates/crm1/customer_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm1/base.html' %}
{% block content %}
    <h1>Edit Customer</h1>
    <form method="POST" class="customer-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}
</html>

crm1/templates/crm1/customer_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm1/base.html' %}
{% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title>Dog Bites</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Dog Bites!
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Customer Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer Name</th>
                <th>Organization</th>
                <th>Role</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Bldg-Room</th>
                <th>Account</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip Code</th>

                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in customers %}
                <tr>
                    <td>{{ customer.cust_name }}</td>
                    <td>{{ customer.organization }}</td>
                    <td>{{ customer.role }}</td>
                    <td>{{ customer.email }}</td>
                    <td>{{ customer.phone_number }}</td>
                    <td>{{ customer.bldgroom }}</td>
                    <td>{{ customer.account_number }}</td>
                    <td>{{ customer.address }}</td>
                    <td>{{ customer.city }}</td>
                    <td>{{ customer.state }}</td>
                    <td>{{ customer.zipcode }}</td>
                    <td><a href="{% url 'crm1:customer_edit' pk=customer.pk %}" class="btn btn-warning">Edit</a>

                    <td><a href="{% url 'crm1:customer_delete' pk=customer.pk %}"
                        onclick="return confirm('Are you sure you want to delete?')"
                        class="btn btn-danger">Delete</a>
                    </td>


                    <td><a href="{% url 'crm1:summary' pk=customer.pk %}"
                           class="btn btn-primary">Summary</a>

                </tr>
            {% endfor %}
            </tbody>
        </table>

      <a href="{% url 'crm1:export_customers' %}">Export all customers</a>



    </div>
    </body>
    </html>
{% endblock %}
</html>

crm1/templates/crm1/product_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ product.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm1:home' pk=product.product_number %} ">Cancel</a>

    </form>

{% endblock %}

</html>

crm1/templates/crm1/product_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm1/base.html' %}
{% block content %}
    <h1>Edit Product</h1>
    <form method="POST" class="product-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}
</html>

crm1/templates/crm1/product_new.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm1/base.html' %}
{% block content %}
    <h1>Add a New Product</h1>
    <form method="POST" class="product-form">{% csrf_token %}
          {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

{% endblock %}

</html>